version: '3'

services:
  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - REDIS_HOST=redis

  redis:
    image: "redis:alpine"

  db:
    image: "postgres:13"
    container_name: 'test-db'
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    ports:
      - '${DB_PORT}:5432'

  worker:
    build: .
    command: ["celery", "-A", "project", "worker", "--loglevel=info"]
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis