services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - redis
      - db
    environment:
      - REDIS_HOST=redis
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS

  redis:
    image: "redis:alpine"

  db:
    image: "postgres:13"
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    ports:
      - '${DB_PORT}:5432'

  worker:
    build: .
    command: ["celery", "-A", "project", "worker", "--loglevel=info"]
    depends_on:
      - redis
    restart: always
    environment:
      - REDIS_HOST=redis
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS